In [1]:
import pandas as pd

df = pd.read_csv('./data/titanic_clean.csv')

print(df.shape)

df.head()

(891, 11)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [3]:
df['Sex'].value_counts()

Sex
1    577
0    314
Name: count, dtype: int64

In [4]:
df['Embarked'].value_counts()

Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [2]:
df['Sex'] = df['Sex'].map({
    'male': 1,
    'female': 0
})

df['Sex'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [5]:
df['Embarked'] = df['Embarked'].map({
    'S': 0,
    'C': 1,
    'Q': 2
})

df['Embarked'].head()

0    0
1    1
2    0
3    0
4    0
Name: Embarked, dtype: int64

In [6]:
df = df.drop([
    'PassengerId',
    'Name',
    'Ticket'
], axis=1)

df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         0
1         1       1    0  38.0      1      0  71.2833         1
2         1       3    0  26.0      0      0   7.9250         0
3         1       1    0  35.0      1      0  53.1000         0
4         0       3    1  35.0      0      0   8.0500         0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int64
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 55.8 KB

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
mms_pclass = MinMaxScaler()
mms_sex = MinMaxScaler()
mms_age = MinMaxScaler()
mms_sibsp = MinMaxScaler()
mms_parch = MinMaxScaler()
mms_fare = MinMaxScaler()
mms_embarked = MinMaxScaler()

In [10]:
df['Pclass'] = mms_pclass.fit_transform(df[['Pclass']])

df['Sex'] = mms_sex.fit_transform(df[['Sex']])

df['Age'] = mms_age.fit_transform(df[['Age']])

df['SibSp'] = mms_sibsp.fit_transform(df[['SibSp']])

df['Parch'] = mms_parch.fit_transform(df[['Parch']])

df['Fare'] = mms_fare.fit_transform(df[['Fare']])

df['Embarked'] = mms_embarked.fit_transform(df[['Embarked']])

In [11]:
df.head()

   Survived  Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         0     1.0  1.0  0.271174  0.125    0.0  0.014151       0.0
1         1     0.0  0.0  0.472229  0.125    0.0  0.139136       0.5
2         1     1.0  0.0  0.321438  0.000    0.0  0.015469       0.0
3         1     0.0  0.0  0.434531  0.125    0.0  0.103644       0.0
4         0     1.0  1.0  0.434531  0.000    0.0  0.015713       0.0

In [12]:
df.to_csv('./data/titanic_procesado.csv', index=False)

print("Archivo guardado correctamente")

Archivo guardado correctamente

In [1]:
import os

print(os.listdir('data'))

['titanic.csv', 'titanic_clean.csv', 'titanic_procesado.csv']